### ISSUE TITLE
[Feature Request] Add A/V Codec Info to Source Select

### ISSUE THREAD

**Issue by eengert** [Goldenfreddy0703/seren.theme.ah2#2]
Could you please add more details on the Source Select window?  It's helpful to know SDR/HDR/DV as well as Audio information - DD/DD+/TrueHD/Atmos and 2.1/5.1/7.1.  I believe all of this is displayed on the default Source Select window.  Better yet, if possible, provide an option for which tags are displayed for each file.

Thanks.

**Comment by Goldenfreddy0703** [comment]
Hey, im very sorry i didn't see this sooner, i never updated the them in a long time and was focusing on my anime addon. You helped me find a glitch with the info tab on source select so i will go ahead and get this fixed for you. 

Thank you.

**Comment by Goldenfreddy0703** [comment]
Hey im going to close this issue but hopefully, you issue is resolved.
